### ISSUE TITLE
playlist数据获取问题

### ISSUE THREAD

**Issue by BeImperfect** [CaiJinyc/vue-music-webapp#12]
player.vue页面获取到的playlist数据是通过getters.js里导入的api/song 来获取的吗

**Comment by CaiJinyc** [comment]
getSong 是用来获取歌曲播放地址的，playlist 数据在每个页面的获取的方式都不一样，比如推荐是通过 getRecommedList 获取，歌手是通过 getSIngerDetail 获取

**Comment by BeImperfect** [comment]
ok, 多谢啦

**Comment by BeImperfect** [comment]
问下，playlist.vue组件导入了getsong后，在下面的watch里引用getSong/getLyric时怎么前面都加了 ‘ _ ’这个符号？是哪里有设置过配置吗还是怎样的

**Comment by CaiJinyc** [comment]
。。。当然是已经在 methods 中定义过了，下次找不到请用 ctrl + F
