### ISSUE TITLE
vue新手提问：点击推荐报错，仿佛因为权限问题

### ISSUE THREAD

**Issue by nyz123** [CaiJinyc/vue-music-webapp#2]

**Comment by nyz123** [comment]
![vue-music-error](https://user-images.githubusercontent.com/16752085/40124953-40bfa4fc-595c-11e8-9f51-51fd8f73eefc.png)

**Comment by CaiJinyc** [comment]
因为服务器的问题，多人同时访问会出现这样的问题，过一会再访问就好了，实在抱歉。
