### ISSUE TITLE
vue2.5.2调用audio的play()移动端无法播放

### ISSUE THREAD

**Issue by wuzhe128520** [caijinyc/vue-music-webapp#25]
楼主，请教下您，有没有遇到过类似的问题，在vue2.5.2中执行audio play()方法，音乐无法播放，下面是我的代码：
`<div class="song-list-wrap" ref="songListWrap">
        <div class="wrapper" v-if="songList && songList.tracks.length">
          <div class="song-item" v-for="song in songList.tracks" :key="song.id" @click.stop="getSong(song.id)">
            <div class="song-name ellipsis">{{ song.name }}</div>
            <p class="song-singer ellipsis">{{ song.ar[0].name }}</p>
          </div>
        </div>
      </div>`
`methods: {
  getSong (id) {
      let musicPlayer = document.getElementById('audio')
      console.log('获取audio对象', musicPlayer)
     // 异步获取歌曲的url
      getSongUrl(id).then(urlData => {
        console.log('获取歌曲url', urlData)
        if (urlData.code === 200) {
          this.songUrl = urlData.data[0].url
          // this.$store.state.musicPlayer
          
          musicPlayer.src = urlData.data[0].url
          musicPlayer.play()
          console.log('musicPlayer', musicPlayer)
        }
   }
}`
这样写，在浏览器下是可以播放的，但是在移动端无法播放；不知道楼主遇到过没？麻烦指点下，先谢谢你了

**Comment by wuzhe128520** [comment]
```html
<div class="song-list-wrap" ref="songListWrap"> 
    <div class="wrapper" v-if="songList && songList.tracks.length">
     <div class="song-item" v-for="song in songList.tracks" :key="song.id" @click.stop="getSong(song.id)"> 
    <div class="song-name ellipsis">{{ song.name }}</div> 
    <p class="song-singer ellipsis">{{ song.ar[0].name }}</p> 
       </div> 
    </div>
 </div>
```

**Comment by wuzhe128520** [comment]
```javascript
methods: {
getSong (id) {
let musicPlayer = document.getElementById('audio')
console.log('获取audio对象', musicPlayer)
// 异步获取歌曲的url
getSongUrl(id).then(urlData => {
console.log('获取歌曲url', urlData)
if (urlData.code === 200) {
this.songUrl = urlData.data[0].url
// this.$store.state.musicPlayer

      musicPlayer.src = urlData.data[0].url
      musicPlayer.play()
      console.log('musicPlayer', musicPlayer)
    }
}
}
```

**Comment by caijinyc** [comment]
移动端游览器限制，无法自动播放。

**Comment by wuzhe128520** [comment]
> 移动端游览器限制，无法自动播放。

不是自动播放，就是手动调用audio.play()

**Comment by caijinyc** [comment]
为什么 audio 不用 ref 获取嘞

我的逻辑是 watch url 的变化，如果 url 变化那么 this.$refs.auido = newUrl

因为 audio 标签已经设置的 autoplay 所以就会自动播放歌曲了。如果设置了 autoplay 就不用手动调用 play() 了呀，你是不是没有加？

**Comment by wuzhe128520** [comment]
> 为什么 audio 不用 ref 获取嘞
> 
> 我的逻辑是 watch url 的变化，如果 url 变化那么 this.$refs.auido = newUrl
> 
> 因为 audio 标签已经设置的 autoplay 所以就会自动播放歌曲了。如果设置了 autoplay 就不用手动调用 play() 了呀，你是不是没有加？

嗯，我没有设置autoplay,是点击歌曲的时候，调用的play()，audio是通过ref获取的，存在vuex里了
