### ISSUE TITLE
歌手列表实现的博客失效了

### ISSUE THREAD

**Issue by Hhpon** [caijinyc/vue-music-webapp#26]
想了好久没法实现这个功能

**Comment by caijinyc** [comment]
@Hhpon emm 博客上因为图片丢了就删掉了，掘金上还有 https://juejin.im/post/5aeaea926fb9a07aac244d41

**Comment by Hhpon** [comment]
请问你数据是怎么处理的呢？歌手按照拼音排序这块我弄不明白了

**Comment by Hhpon** [comment]
歌手的数据这块你是用的nete的那个网易云api嘛？

**Comment by caijinyc** [comment]
@Hhpon  https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=neteasecloudmusicapi
