### ISSUE TITLE
新手提问：npm install执行过程有很多警告，标红的不太理解，能否帮忙看一下

### ISSUE THREAD

**Issue by nyz123** [CaiJinyc/vue-music-webapp#3]
![npm-error](https://user-images.githubusercontent.com/16752085/40124944-39224b46-595c-11e8-8fea-4cef00750ece.png)

**Comment by bluker** [comment]
https://github.com/nodejs/node-gyp#installation

**Comment by liukai5566** [comment]
[图片]
