### ISSUE TITLE
推荐页面的歌单，点击后获取不到具体的歌曲

### ISSUE THREAD

**Issue by angrebobo** [CaiJinyc/vue-music-webapp#37]

**Comment by Ericxxt** [comment]
我也是，我在国外怀疑是服务器的问题，然后网易云文档说需要在网易云api的/utils/request.js 中改变header的服务器。但是我改变了没有用

**Comment by angrebobo** [comment]
> 我也是，我在国外怀疑是服务器的问题，然后网易云文档说需要在网易云api的/utils/request.js 中改变header的服务器。但是我改变了没有用

我已经改好了，其实是api接口变了。你去song.js里面找那个recommendsonglist（）方法，然后把api接口的参数改一下
