### ISSUE TITLE
项目跑起来之后，没有数据。控制台报错，一片红。

### ISSUE THREAD

**Issue by liukai5566** [CaiJinyc/vue-music-webapp#4]
1无法上图，原谅我是一个小白。
Failed to load http://120.79.162.149:3000/personalized: The 'Access-Control-Allow-Origin' header has a value 'http://120.79.162.149:3002' that is not equal to the supplied origin. Origin 'http://localhost:8080' is therefore not allowed access.
给解答一下。。。。

**Comment by CaiJinyc** [comment]
过一会再访问就好，API 炸了。

**Comment by nyz123** [comment]
我觉得吧，不要问重复问题
